### ISSUE TITLE
FOOTER

### ISSUE THREAD

**Issue by Akanksha-Sen** [siddhi-244/Embellish#289] opened 2022-07-31 18:17 UTC
**Is your feature request related to a problem? Please describe.**
Footer

**Describe the solution you'd like**
Want to add footer section.

**Comment by siddhi-244** [comment] 2022-08-02 08:46
> **Is your feature request related to a problem? Please describe.** Footer
> 
> **Describe the solution you'd like** Want to add footer section.

We don't need it

**Comment by siddhi-244** [comment] 2022-08-03 08:44
Closing this as the issue is not descriptive

**Closed by siddhi-244** 2022-08-03 08:44 UTC
